import Head from "next/head";
import { Provider } from "react-redux";
import store from "../store/index";
import "../styles/globals.css";


const MyApp = ({ Component, pageProps }) => {
  
  const NoLayout = ({ children }) => <>{children}</>;
  const Layout = Component.Layout || NoLayout;
    
  return (
    <Provider store={store}>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  );
};

export default MyApp;